### PR TITLE
2024.08 DeltaFPS

### PR DESCRIPTION
**Pull request by brad-linden**
as of = 2024-09-11 for RC deploy
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2394453ae-DeltaFPS
cohort = DeltaFPS
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2394453ae-DeltaFPS
desired = 5000
relnotes:

### DeltaFPS

This release brings some much anticipated performance boosts. Memory management has been optimized and users will experience a higher FPS across various systems. A comprehensive range of bug fixes are also provided. This includes better PBR material handling and resolving frequent crashes. See the list below for more info.

Prefer to have your region restarting while you're asleep? UI for scheduling region restarts has been added and can be accessed via a new button located in the Region/Estate floater. (Note: there is currently an issue with scheduled region restarts working correctly and a fix is due to come in the next server release)

For users wanting to stop their avatar always looking where their mouse cursor is (like a cat chasing a laser pointer), there is now an option to prevent this! The "Disable Look At Animation" option is currently under Develop>Avatar>Character Tests

### CODE REVIEW

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23a0da63d-DeltaFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231adf2d0-DeltaFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2350dc4cb-DeltaFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%238406d10-DeltaFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b0fefd6-DeltaFPS1

**Comment by AtlasLinden** [comment]
| DeltaFPS RC 7.1.10.10622905308 | Result | Comment | 
|---|---|---|
| secondlife/iqa#323 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
No blockers. 

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
DeltaFPS RC approved.
viewer = 7.1.10.10622905308
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b0fefd6-DeltaFPS1
cohort = DeltaFPS
desired = 3000

**Comment by AtlasLinden** [comment]
| DeltaFPS RC 7.1.10.10708851543 | Result | Comment | 
|---|---|---|
| secondlife/iqa#326 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
HD4000 is still hitting https://github.com/secondlife/viewer/issues/2434

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
DeltaFPS RC approved
viewer = 7.1.10.10708851543
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23d5446b3-DeltaFPS
cohort = DeltaFPS
desired = 3000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23d5446b3-DeltaFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2394453ae-DeltaFPS

**Comment by Dan-Linden** [comment]
| DeltaFPS RC 7.1.10.10800445603 | Result | Comment |
|---|---|---|
| secondlife/iqa#332 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** |

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
DeltaFPS RC approved.
viewer = 7.1.10.10800445603
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2394453ae-DeltaFPS
cohort = DeltaFPS
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2394453ae-DeltaFPS

**Review by kylelinden — APPROVED** [review]
DeltaFPS promotion to default approved.
Promotion checklist complete with review.
Hours, crash rate, avg FPS, commits.

viewer = 7.1.10.10800445603
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2394453ae-DeltaFPS
cohort = DeltaFPS
desired =

**Pull request merged**
