### PR TITLE
Fix the filter in Inventory-Favorites (#2856 regression)

### PR DESCRIPTION
**Pull request by marchcat**
This filter didn't work after the merge for some reason; it seems that setFilterFavorites() should be called there, so I added it.

### CODE REVIEW

**Review by akleshchev — CHANGES_REQUESTED** [review]
This shouldn't be needed. This panel uses special favorites_inventory_panel (due to hierarhy changes) and it displays both favorite items and non-favorite content of favorite folders, so filter is likely to break intended behavior for this panel.

Edit: I think I found the problem (initRootContent() is missing), building and checking.

**Comment by marchcat** [comment]
Thank you!

**Comment by marchcat** [comment]
Right, the code is present, but not for LLInventoryFavoritesItemsPanel.

**Comment by marchcat** [comment]
It works like a charm now 😸

**Comment by marchcat** [comment]
Closing since 35edd296a6f850b811c000c8b337abaa1fde9835 is already integrated.

**Pull request closed without merging**
