### PR TITLE
Maintenance YZ

### PR DESCRIPTION
**Pull request by marchcat**
+ DRTVWR-594 Maint Y
+ DRTVWR-599 Maint Z

relnotes:
### Maintenance: Yeet Dan’s Bugs (bonus Maint Z integration)
Context menus in the Outfit floater have been given a revamp in this release and users will be able to preview their breathtaking outfit photos when hovering their cursor down the My Outfits tab.

Residents that have been pulling their hair out every time the navigation bar suggests a hair store’s old location can now leave their hair unpulled as there is now an option to remove locations from history. This can be performed via the context menu located in the Places floaters Visited tab.

Several fixes to Classifieds and Picks that have been long standing friction points.

*Reverted* [BUG-234241](https://jira.secondlife.com/browse/BUG-234241) Setting shape hand size to 36 won't save - to resolve reports of the [Avatar Shape Slider Values](https://secondlife.canny.io/bug-reports/p/avatar-shape-slider-value-changes) being wrong.

BONUS: Minor bug fixes! See below for more info.

### CODE REVIEW

**Comment by marchcat-pe** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f0faf5-yz

**Comment by AtlasLinden** [comment]
| Maint YZ RC 7.1.3.7790341084 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#118 Acceptance, Smoke & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious <br> Yandex - Trojan.PyInstaller!7Lr0/TMk2fI |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Review by kylelinden — APPROVED** [review]
Approved Maint YZ for RC update 7.1.3.7790341084
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f0faf5-yz
cohort = Maintenance-Y
desired = 3000

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2343049bc-yz

**Comment by AtlasLinden** [comment]
| Maint YZ RC 7.1.4.8114240508 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#149 Acceptance, Smoke & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Cynet - Malicious (score: 100) <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Approved Maint YZ RC
viewer: 7.1.4.8114240508
build: https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2343049bc-yz
cohort: Maintenance-Y
desired: 3000

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2343049bc-yz

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2316e638d-yz

**Review by kylelinden — APPROVED** [review]
Maint YZ RC approved
viewer = 7.1.5.8448596295
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2316e638d-yz
cohort = Maintenance-Y
desired = 3000

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235118ba7-yz

**Comment by AtlasLinden** [comment]
| Maint YZ RC 7.1.6.8632452945 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#189 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |
| uninst.exe | Bkav Pro - W32.AIDetectMalware |

**Review by kylelinden — APPROVED** [review]
Maint YZ RC approved
version = 7.1.6.8632452945
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235118ba7-yz
cohort = Maintenance-YZ
desired = 3000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235118ba7-yz

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235e40b5e-yz

**Comment by Dan-Linden** [comment]
| Maint YZ RC 7.1.6.8745209917 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#189 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |
| SLVoice.exe | Bkav Pro - W32.AIDetectMalware |
| uninst.exe | Bkav Pro - W32.AIDetectMalware |

**Review by kylelinden — APPROVED** [review]
Maint-YZ RC approved
viewer = 7.1.6.8745209917
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235e40b5e-yz
cohort = Maintenance-YZ
desired = 3000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235e40b5e-yz

**Review by kylelinden — APPROVED** [review]
Approved for promotion to default release.

**Pull request closed without merging**
