### PR TITLE
Revert the "Update emoji_categories in Polish translation"

### PR DESCRIPTION
**Pull request by PanteraPolnocy**
The reason of reverting this one is the fact, that the grammar errors and typos - not only in Polish language, but in German and all the rest - are all around 3P packages as well, so updating category names in the viewer will break the connection with the 3P. Who had the bright idea of designing it like that and not exposing it for translators to correct? Not to mention, why on earth the EMOJI CODES are translated as well, instead of - for example - tooltip names? Everyone in Poland would look for :potato: and not a :ziemniak:

### CODE REVIEW

**Comment by PanteraPolnocy** [comment]
... even Github changes : potato : to an actual :potato:

**Comment by PanteraPolnocy** [comment]
For reference, I found this. https://github.com/secondlife/jira-archive/issues/11824

**Review by akleshchev — APPROVED** [review]

**Review by marchcat — APPROVED** [review]

**Comment by akleshchev** [comment]
Yeah, bad design, git fails to merge this, will do a separate commit.

**Comment by marchcat** [comment]
@PanteraPolnocy Thank you for noticing this problem, we'll fix this in the upcoming release.

**Comment by PanteraPolnocy** [comment]
@marchcat I cannot take creadit here, as it was @Ansariel who pointed that issue out when I grumbled about the state of this file in our repository; She warned, that 3p packages will be a problem here.

**Comment by akleshchev** [comment]
And here I though that thing was fixed...

**Pull request closed without merging**
