### PR TITLE
Add Develop menu option 'Debug Camera Controls'

### PR DESCRIPTION
**Pull request by LLGuru**
It is useful for investigating camera behavior issues like https://github.com/secondlife/jira-archive-internal/issues/69593

image

### CODE REVIEW

**Comment by marchcat** [comment]
Doesn't this duplicate Develop -> Consoles -> Camera?

**Comment by LLGuru** [comment]
> Doesn't this duplicate Develop -> Consoles -> Camera?

Absolutely not
1. This tool shows info for two cameras: Viewer Camera and Agent Cameera
2. This tool shows the original values stored in the class vriables, and not calculated
3. This tool relates to the CAMERA CONTROLS floater because it shows the result
4. This tool is placed inside the CAMERA CONTROLS floater and looks more readable

**Comment by marchcat** [comment]
Okay, in this case, calling it from the menu should (_probably_) open a camera controls panel if it's not already visible.
Also, merging these two tools into one might be advisable. However, I still have no opinion on this matter.

**Comment by akleshchev** [comment]
> Also, merging these two tools into one might be advisable.
Agree, I would rather have Consoles -> Camera be updated to show more info.

**Review by akleshchev — APPROVED** [review]
I don't see issues code wise, but 'feature' wise I suggest asking vir or getting more input about desired behavior elsewhere.

**Review by marchcat — APPROVED** [review]

**Comment by vir-linden** [comment]
I'm good moving forward with this design

**Pull request merged**
