### PR TITLE
Use libdecor for SDL

### PR DESCRIPTION
**Pull request by AiraYumi**
Enables native support for the Wayland desktop environment.

Extract only the commits you need from #2749 .

Related Issues : https://github.com/secondlife/viewer/issues/1442 [Linux] Add Native Support for Wayland

- [x] Compile viewer
- [x] Allows you to launch the viewer.
- [x] Use libdecor for GNOME

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

**Comment by marchcat** [comment]
Approved the PR instead of approving the build 😹

**Comment by AiraYumi** [comment]
This can be merged after #2918 is merged.

**Comment by RyeMutt** [comment]
I'm opposed to defaulting to the SDL wayland backend when on a wayland session due to SDL still working out many compatibility issues.

**Comment by AiraYumi** [comment]
Sdl wayland backend has been disabled.

**Comment by AiraYumi** [comment]
@marchcat @RyeMutt Should I abandon this RP?
Should I wait until SDL is wayland compatible?

I don't think there will be any impact on operation if you don't make this change.

**Comment by marchcat** [comment]
@AiraYumi, we should probably try to use less dependencies where it's possible.
However, I have no opinion regarding libdecor. Looks like SDL should be enough.

**Comment by AiraYumi** [comment]
I will discard this RP for now.
I will wait until SDL's wayland support is stable.

**Pull request closed without merging**
