### PR TITLE
SL-20453 Fix dupplicate items in menu

### PR DESCRIPTION
**Pull request by akleshchev**
Cleanup. Caused by a merge of main(D567) into D559

### CODE REVIEW

**Comment by Ansariel** [comment]
Not all of those appear to be duplicate - at least not in menu_inventory.xml

**Comment by akleshchev** [comment]
QA reported seeing dupplicates of "Use as default for", "New Folder" and most creation options were removed in D567.

I checked what should be present, then just moved menu_inventory.xml from release into pbr and readded "PBR uploads".

**Comment by Ansariel** [comment]
Ah yes. That weird UI design. Something for me to ignore when merging. :D

**Review by marchcat-pe — APPROVED** [review]

**Comment by akleshchev** [comment]
>Ah yes. That weird UI design. Something for me to ignore when merging. :D
Looks like it will be added back in SL-20457

**Pull request merged**
