### PR TITLE
Add dedicated sun probe shader and remove SSAO and shadow smoothing from probe generation passes

### PR DESCRIPTION
**Pull request by RyeMutt**
* Disable SSAO and shadow smoothing and add dedicated sun shader without ssao for probes
* Remove reference to dead sunLightNoFragCoordV shader

#2398

### CODE REVIEW

**Comment by RyeMutt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ansariel** [comment]
Are the shader files missing?

**Comment by RyeMutt** [comment]
The sun shader files are reused for this. I created a variant that always loads the non-ssao sun shader.

**Comment by Ansariel** [comment]
Weird! I can't find sunLightNoFragCoordV.glsl anywhere...

**Comment by RyeMutt** [comment]
Good catch. Looks like that was removed a while ago.

**Comment by Ansariel** [comment]
And the other ones are only availble on shader level >= 2 - not sure if you check for that, so just FYI

**Review by RunitaiLinden — APPROVED** [review]

**Pull request merged**
