### PR TITLE
Maintenance C

### PR DESCRIPTION
**Pull request by marchcat**
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c137e6a-c
cohort = Maintenance-C
desired = 2000
as of = 2024-06-14 for RC deploy
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c137e6a-c
relnotes:

### Maint C: Cthulodon

Cthulodon[,](https://wiki.secondlife.com/wiki/File:Cthulodon.webp) a completely made up fictional beast that has the tentacles characteristic of Cthulu as well as dinosaurian traits which together create something truly terrifying. Fortunately, such a creature would likely only be found in the world of Second Life and could possibly be the result of an avatar requiring their skeleton to be reset.

Previously, the magic to reset your avatar only worked locally but with this release, resetting your avatars skeleton will now reset it for others too! 

Find more about other included fixes listed below.

### CODE REVIEW

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23e5b14e4-c

**Comment by AtlasLinden** [comment]
| Maint C RC 7.1.7.8820704257 | Result | Comment | 
|---|---|---|
| secondlife/iqa#211 Acceptance, Smoke & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |
| slvoice.exe | Bkav Pro - W64.AIDetectMalware |
| uninst.exe | Bkav Pro - W32.AIDetectMalware |

**Review by kylelinden — COMMENTED** [review]
Maint C RC approved
viewer = 7.1.7.8820704257
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23e5b14e4-c
cohort = Maintenance-C
desired = 1000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23e5b14e4-c

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%234ddaeb3-c

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23e8de17d-c

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c137e6a-c

**Comment by AtlasLinden** [comment]
| Maint C RC 7.1.9.9469671545 | Result | Comment | 
|---|---|---|
| secondlife/iqa#259 Acceptance, Smoke & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Maint C RC approved
viewer = 7.1.9.9469671545
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c137e6a-c
cohort = Maintenance-C
desired = 2000

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c137e6a-c

**Comment by larsnaesbye** [comment]
What prohibits this from getting merged?

**Comment by marchcat** [comment]
The testing is almost finished; after that, this PR will be merged.

**Comment by marchcat** [comment]
This one should be good to merge into `develop` after merging #3067.

**Comment by marchcat** [comment]
This one was accidentally merged along with #3239 (and reverted with #3241). The new PS should be used for further integration.

**Comment by marchcat** [comment]
New PR: #3243.

**Pull request merged**
