### PR TITLE
Various repo fixes

### PR DESCRIPTION
**Pull request by FelixWolf**
These fixes include:

1. Dark theme compatible markdown that uses black on white text if light theme(original), or the white on black text if dark theme(addition). The addition is version I modified to match that of the forum's dark theme:
Old:
Screenshot_20221118_063059
New:
Screenshot_20221118_063121

Issues: I have no idea if bitbucket supports HTML markdown. By markdown standard, it should, but would be worth double checking if bitbucket is still intended to be pushed to.

2. LGPL-licence.txt renamed to LGPL-license.txt. Licence is the verb to give a license, License is the noun of a document. (Note, github sees this as a file move for some reason)
3. Added copy of LGPL-license.txt as LICENSE.txt so that github recognizes it as a license and displays it as such on the sidebar. (Note, github sees this as a new file for some reason)

### CODE REVIEW

**Comment by bennettgoble** [comment]
Hey, @FelixWolf. Thanks for the PR. Could you pull in the latest changes from master in order to incorporate our new CLA bot?

**Review by bennettgoble — CHANGES_REQUESTED** [review]
Could you use `LICENSE` instead of `LICENSE.txt`? This would match the name being used in our other public repositories such as [autobuild ](https://github.com/secondlife/autobuild) and [leap](https://github.com/secondlife/leap). :)

**Comment by FelixWolf** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by FelixWolf** [comment]
h

**Review by bennettgoble — APPROVED** [review]
LGTM. The README looks much better in dark mode now.

**Pull request merged**
