### PR TITLE
Maint B -> develop merge

### PR DESCRIPTION
**Pull request by marchcat**
> [!Note]
> Close this one after merging #2494

Updated version of Maint B (#940) for further integration.

### CODE REVIEW

**Comment by Nicky-D** [comment]
Those failing includes need to be SDL2/SDL.h

Looks like something got clobbered during the merge

**Comment by marchcat** [comment]
> Those failing includes need to be SDL2/SDL.h
> 
> Looks like something got clobbered during the merge

Right, I'm working on that now.

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Project_B_Develop%232ee039c

**Comment by Nicky-D** [comment]
Is there any ETA when this will be merged and Linux changed can continue in develop?

**Comment by marchcat** [comment]
It's being tested now.
As for merge into develop - it will likely happen right after #1829 release.

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Project_B_Develop%238156917

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23e25d23a-b

**Comment by AiraYumi** [comment]
When will this be merged?
Will it be before KDU and Havok are enabled (Release builds are enabled) or after?

**Comment by marchcat** [comment]
> When will this be merged?

Hopefully soon. But it's a big change so it should be tested properly.


> Will it be before KDU and Havok are enabled (Release builds are enabled) or after?

Release builds on Linux? I'm not sure if there are any plans to enable them at the moment.

**Comment by marchcat** [comment]
#2494 merged. Closing.

**Pull request closed without merging**
