### PR TITLE
Release/materials featurette

### PR DESCRIPTION
**Pull request by RunitaiLinden**
as of = 2024-06-05 for RC deploy
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f97ff7-pmfp
cohort = Materials Featurettes
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f97ff7-pmfp
desired = 5000

relnotes:
## Materials Featurettes

Featurettes (Mirrors, PBR Terrain and 2k textures) are now available to all of Second Life. 

Realistic Mirrors are finally in Second Life! PBR Materials reflections are great too, but they are not mirrors.

PBR Terrain is now available on private regions, which is a first step towards making the ground look much more lush and immersive. 

2048 x 2048 (2k) textures - 4 times bigger than 1k are here to stay!

### Additional notes for this release

- Second Life will only render the single closest planar reflection probe.
- With Mirrors enabled residents should expect a decrease in performance since everything is being rendered twice. 
- PBR Terrain is only available on private regions at this time.
- Uploading 2k textures as part of bulk uploads will incur the higher 2k texture upload fee, which is implicitly agreed to during a bulk upload. See known issues below.
- Texture scaling occurs before we calculate upload fees, see https://wiki.secondlife.com/wiki/Limits#All_Viewers for guidelines. 
- A 2048 x 512 texture upload will cost the same as a 1024 x 1024 because it is exactly the same number of pixels.
- 2k textures for Bakes on Mesh (BoM) is coming, meanwhile, please do not start creating 2k onion skin avatars.
- HDRI sky previews are now available to experiment with, in the Develop menu and we'd love to get your feedback on what you can imagine doing with them.

Along with several GLTF PBR materials fixes to make all our residents and our third party developers lives a little bit easier.

Please see this blog post for more information about the features: https://community.secondlife.com/blogs/entry/15291-mirrors-pbr-terrain-and-2k-textures/

#### Known Issues

- #1042 Add tool to "Show Mirror Volumes" <br>
- #1445 (PBR) Moon clips with skydome <br>
- #1493 Nearby avatars stop updating in mirrors when they are outside the camera frustum <br>
- #1506 The Dynamic probe checkbox does not set or display the value correctly <br>
- https://github.com/secondlife/viewer-private/issues/124 When uploading a model with a 2048x2048 texture, the resolution of the uploaded texture is converted to 1024x1024 <br>
- https://github.com/secondlife/viewer-private/issues/128 The planar reflection (mirror) probe isn't displayed on the mirror object until the user relogs <br>
- Mirrors (planar reflection probes) created in Featurettes versions before 7.1.8.9103842320 will default to only reflecting the Environment, please update your Mirror's settings to include Avatars if desired.
- #1652 Spherical mirror probes are disabled for now. Box mirror probes are functional.
- https://github.com/secondlife/jira-archive-internal/issues/71030 [PBR] [Mac] Turning shadows on makes items with alpha blend textures disappear on older Macs. Workaround: Use the Preferences > Graphics > Quality & speed slider.
- https://github.com/secondlife/viewer/issues/1666 Texture Uploads need enhanced options to support 2k and lower resolutions to better predict upload fee

### CODE REVIEW

**Comment by RunitaiLinden** [comment]
Milestone: https://github.com/secondlife/viewer-issues/milestone/3

**Comment by brad-linden** [comment]
secondlife/viewer#977 should also be fixed

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23665d59d-pmfp

**Comment by Dan-Linden** [comment]
| Featurettes RC 7.1.4.8270899680 | Result | Comment | 
|---|---|---|
| secondlife/iqa#161 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Featurettes RC approved
viewer = 7.1.4.8270899680
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23665d59d-pmfp
cohort = Materials Featurettes
desired = 500

**Comment by AtlasLinden** [comment]
| Featurettes RC 7.1.5.8472515256 | Result | Comment | 
|---|---|---|
| secondlife/iqa#179 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |
| slplugin.exe | SecureAge - Malicious |

**Comment by AtlasLinden** [comment]
| Featurettes RC 7.1.5.8472515256 | Result | Comment | 
|---|---|---|
| secondlife/iqa#179 Acceptance & Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
Terrain is blurry on some macs: https://github.com/secondlife/viewer/issues/989

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |
| slplugin.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Featurettes RC approved
viewer = 7.1.5.8472515256
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23617436b-pmfp
cohort = Materials Featurettes
desired = 500

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2386c0c1d5-pmfp

**Comment by Dan-Linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%238465a8a-pmfp

**Comment by Dan-Linden** [comment]
| Featurettes RC 7.1.7.8852879962 | Result | Comment | 
|---|---|---|
| secondlife/iqa#212 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |
| SLVoice.exe | Bkav Pro - W64.AIDetectMalware |
| uninst.exe | Bkav Pro - W32.AIDetectMalware |

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2366ccc1e-pmfp

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2366ccc1e-pmfp

**Review by kylelinden — CHANGES_REQUESTED** [review]
Featurettes RC holding for more fixes.

**Comment by Dan-Linden** [comment]
We've hit the limit of IQAs that can be linked in the Development section. The next IQA is:
- https://github.com/secondlife/iqa/issues/218

**Review by kylelinden — APPROVED** [review]
Featurettes RC approved
viewer = 7.1.7.8883017948
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2366ccc1e-pmfp
cohort = Materials Featurettes
desired = 1000

**Comment by Dan-Linden** [comment]
The next IQA is 
- https://github.com/secondlife/iqa/issues/221

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%236a43bbd-pmfp

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2365c9386-pmfp

**Comment by Dan-Linden** [comment]
| Featurettes RC 7.1.8.9103842320 | Result | Comment | 
|---|---|---|
| secondlife/iqa#221 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Elastic - Malicious (moderate Confidence) <br> SecureAge - Malicious |
| win_crash_logger.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Featurettes RC approved
viewer = 7.1.8.9103842320
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2365c9386-pmfp
cohort = Materials Featurettes
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2365c9386-pmfp

**Comment by Dan-Linden** [comment]
| Featurettes RC 7.1.8.9357006492 | Result | Comment | 
|---|---|---|
| secondlife/iqa#249 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Featurettes RC approved
viewer = 7.1.8.9357006492
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2301c8264-pmfp
cohort = Materials Featurettes
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2301c8264-pmfp

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231f17c7f7-pmfp

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f97ff7-pmfp

**Comment by Dan-Linden** [comment]
IQA for the absolutely, definitely, for sure, last build of this branch is https://github.com/secondlife/iqa/issues/252

**Comment by Dan-Linden** [comment]
| Featurettes RC 7.1.8.9375512768 | Result | Comment | 
|---|---|---|
| secondlife/iqa#252 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Materials Featurettes RC approved.
viewer = 7.1.8.9375512768
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f97ff7-pmfp
cohort = Materials Featurettes
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f97ff7-pmfp

**Review by kylelinden — APPROVED** [review]
Materials Featurettes approved for promotion to default release
viewer = 7.1.8.9375512768
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f97ff7-pmfp
cohort = Materials Featurettes
desired =

**Pull request merged**
