### PR TITLE
fix xcode-16 build

### PR DESCRIPTION
**Pull request by AiraYumi**

### CODE REVIEW

**Comment by AiraYumi** [comment]
Can you check if you can build it?

**Comment by AiraYumi** [comment]
Thank you @nat-goodspeed.
You can probably build it with a new option, but it's probably best not to use it - if you can get it to work this PR might not be necessary.

**Comment by nat-goodspeed** [comment]
The `lerp()` conflict is addressed in the target marchcat/xcode-16 branch.

I think I'll also try to resolve the ambiguous-reversed-operator conflict in source code on that branch. Thank you for pointing out the issue though!

**Comment by AiraYumi** [comment]
I'm glad I could help you fix it.

**Comment by AiraYumi** [comment]
This PR is no longer in use so we are closing it.

**Pull request closed without merging**
