### PR TITLE
Fix various sources of stutter from findChild during draw

### PR DESCRIPTION
**Pull request by RyeMutt**
This fixes various sources of excessive findChild recursion during UI draw

### CODE REVIEW

**Review by marchcat — APPROVED** [review]
Thank you!

**Comment by marchcat** [comment]
Pre-commit fails with
```
Check Indentation (Spaces)...............................................Failed
- hook id: indent-with-spaces
- exit code: 1

indra/newview/llviewermenu.cpp: 10 lines starting with tabs found
```

Please fix this so we can proceed.

**Review by akleshchev — APPROVED** [review]

**Comment by RyeMutt** [comment]
Should be good to go now!

**Comment by marchcat** [comment]
The check is green now, merging.

Thank you for your efforts!

**Pull request merged**
