### PR TITLE
Revert removal of llphysicsextension_stub for Windows

### PR DESCRIPTION
**Pull request by nerodevo**
This reverts commit d07cd115e3bdef8a2b1d2f6a5a507ddb67ff8cd9.

Was getting a cmake error related to the llphysicsextension_stub package. I provided a comment in the commit that shows the error log. Reverting this change resolves the error.

### CODE REVIEW

**Comment by Nicky-D** [comment]
This should be made a windows64 package to prevent another accidental removal in the future

**Review by nat-goodspeed — CHANGES_REQUESTED** [review]
I'm glad this fixes the problem, but I agree with Nicky and Marchcat.

**Comment by nat-goodspeed** [comment]
I'm embarrassed to admit that we haven't yet reconstructed automated builds for `_stub` since migrating to GitHub. There are some anomalies we haven't yet resolved.

**Comment by nerodevo** [comment]
> I'm embarrassed to admit that we haven't yet reconstructed automated builds for `_stub` since migrating to GitHub. There are some anomalies we haven't yet resolved.

No worries. It'll eventually get there. BTW, you requested some changes the other day but nothing specific mentioned code-wise. Should I ignore that?

**Comment by nat-goodspeed** [comment]
What Nicky said.  :-)

**Comment by Nicky-D** [comment]
@nerodevo I left you two comment what to change, basically it is a replacement of 
`<string>windows</string>`
to
`<string>windows64</string>`

@nat-goodspeed I think when working making the stub public, it can also be made a common (I think it is source only)

Though I still entertain the idea to PR the HACD based mesh uploader to kill the stub

**Comment by nerodevo** [comment]
Thanks @Nicky-D . Initially I thought ya'll were speaking in general as if it would eventually be made windows64 once the packaging is done. Pardon the double commit... Shuffling between things on my end and got in a hurry.

**Review by Nicky-D — COMMENTED** [review]
Looks good to me

**Review by nat-goodspeed — APPROVED** [review]

**Review by marchcat — APPROVED** [review]
Thanks for the contribution!

@nat-goodspeed, should we merge this to the closest Maint?

**Comment by nat-goodspeed** [comment]
Sounds good, @marchcat .

**Pull request merged**
