### PR TITLE
Allow triggering an EDU build with a tag containing "edu"

### PR DESCRIPTION
**Pull request by nat-goodspeed**

### CODE REVIEW

**Comment by nat-goodspeed** [comment]
This isn't meant to merge directly to main. It's meant to produce an EDU build based on main, but meanwhile please glance over the change to `build.yaml`. (Suppressing whitespace is probably useful.)

**Comment by nat-goodspeed** [comment]
e.g. [this Mac build](https://github.com/secondlife/viewer/actions/runs/10372877675/job/28716648458#step:10:181)

**Review by brad-linden — APPROVED** [review]

**Comment by nat-goodspeed** [comment]
Brad, I've retargeted to develop, this time with intent to merge. Please take another look, again with whitespace differences suppressed.

**Review by brad-linden — APPROVED** [review]
looks good for develop

**Review by marchcat — APPROVED** [review]

**Pull request merged**
