### PR TITLE
secondlife/viewer#1200 Avatar rotates 360 degrees when viewed from the top and below

### PR DESCRIPTION
**Pull request by LLGuru**
Fix for https://github.com/secondlife/viewer/issues/1200
Cherry-pick from https://github.com/secondlife/viewer/pull/1240

### CODE REVIEW

**Review by marchcat — COMMENTED** [review]
Hmm, was it also messed up by the merge in Maint C?

**Comment by marchcat** [comment]
I mean, there was a conflict in Maint A, but I hadn't noticed it here...

**Review by marchcat — APPROVED** [review]

**Comment by akleshchev** [comment]
> Hmm, was it also messed up by the merge in Maint C?

@marchcat No, this commit was dropped during YZ release as not tested and not present in latest RC.

**Review by akleshchev — APPROVED** [review]

**Comment by marchcat** [comment]
Makes sense, thank you.

**Pull request merged**
