### PR TITLE
DRTVWR-489: Emoji Support

### PR DESCRIPTION
**Pull request by nat-goodspeed**
Some testing and product/UX related notes:

* You can pick emoji in chat by doing : + whatever search term
  * List of valid words and associated Emoji characters can be found here: https://raw.githubusercontent.com/secondlife/viewer/DRTVWR-489-emoji/indra/newview/skins/default/xui/en/emoji_characters.xml
* You can also add emojis using the system picker (on windows, win-.)
* Emoji search by name is currently not localized, only works in english. Is support for other languages required?
* (personal observation) emojis look pretty small, maybe they should be larger than regular text?
* typical apps with emoji support also let you choose emojis from a tabbed grid, is this required for us?

relnotes:

#### Emoji ####
Welcome to emojis 👋 😀! This viewer is based on a contribution by Kitty Barnett, and adds the ability to insert and display emojis in text chat and other useful places. Emojis are encoded as their corresponding unicode characters and may be accessed from the chat interface.

Many thanks to Kitty 🐈  for the initial submission and much followup and revision.

Please remember to file any new Feature Requests or Bug Reports at https://feedback.secondlife.com

### CODE REVIEW

**Comment by nat-goodspeed** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23f6ceafe-emoji
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%237d4de08-emoji
cohort = Emoji
desired = 3000

**Comment by marchcat-pe** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23cc43f42-emoji

**Comment by Dan-Linden** [comment]
| Emoji Support RC 7.1.3.7659007892 | Result | Comment | 
|---|---|---|
| secondlife/iqa#97 Acceptance, Integration & Additional tests | Failed | Failed |
| **Overall Result** | **Failed** | **Not ok to ship** | 

**NOTES**
Blocked by https://github.com/secondlife/triage/issues/67

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious <br> Yandex - Trojan.PyInstaller!7Lr0/TMk2fI |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Comment by LLGuru** [comment]
Hi @Dan-Linden 

Regarding this note:
image

I guess https://github.com/secondlife/triage/issues/67 is not a blocker
I removed this TextEdit field from UI because it can't work now as before
The picker is focusless: while it is shown, the focus is still in the ChatEditor

As I wrote in the comment to the issue, user can see the entered filter text
in the emoji description area (at the bottom of the picker) and in ChatEditor

It seems the test plan should be reworked accordingly to this change,
and all tests related to that Search field may be removed

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b4e29ec-emoji

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231820095-emoji

**Comment by Dan-Linden** [comment]
| Emoji Support RC 7.1.3.7878383867 | Result | Comment | 
|---|---|---|
| secondlife/iqa#127 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious <br> Yandex - Trojan.PyInstaller!7Lr0/TMk2fI |
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Comment by brad-linden** [comment]
recheck

**Comment by brad-linden** [comment]
recheck

**Review by kylelinden — APPROVED** [review]
Approved Emoji RC (with spurious CLA warning)
viewer = 7.1.3.7878383867
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231820095-emoji
cohort = Emoji 
desired = 5000

**Comment by nat-goodspeed** [comment]
Um. That build link will choke the release script, since it's not really a build link but a compare link.

**Comment by Dan-Linden** [comment]
Sent https://github.com/secondlife/iqa/issues/137 through QA. No blockers.

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231820095-emoji

**Comment by Dan-Linden** [comment]
Emoji PR cleanup - https://docs.google.com/document/d/1I3y4rl-8UP8VQzRI6AZF8oWqSgbnotrgCqrX4J_YSkQ/edit

**Pull request closed without merging**
