### PR TITLE
#824 Replace tab indents with spaces in Maint X

### PR DESCRIPTION
**Pull request by marchcat**

### CODE REVIEW

**Comment by Ansariel** [comment]
Where is the documentation how to merge this without getting 3475893649360 merge conflicts?

**Comment by marchcat** [comment]
I'll update it soon as well. Conflicts should be minimal (if any at all).

**Comment by Ansariel** [comment]
The fix_whitespace.py script doesn't even work. Whatever I try as parameters, I always get a syntax error in line 68.

P.S.: Should use the script to convert spaces to tabs instead...

**Comment by Ansariel** [comment]
I still got some info from Signal on how to merge this from his previous attempt on forcing this nonsense down everyone's throat - that kinda works, but the new fix_whitespace.py script just doesn't even work for me now.

And all this because at some point in the past some developers couldn't figure out how to enable tabs as indendation as it has been default für C++ projects in Visual Studio since forever and starting to create the mess we see today. It's obvious tabs are far more superior than spaces for indentation (personal preference in indendation width, simplicity in text navigation), and yet this gets pursued regarding all the negative feedback, especially since this adds no value or benefit at all, but disrupts everyone.

**Comment by marchcat** [comment]
> Whatever I try as parameters, I always get a syntax error in line 68.

`cd viewer\scripts\code_tools\`
`python.exe .\fix_whitespace.py -d ..\..\indra`
Other parameters are not required.


Before doing that, `git merge --no-commit -Xignore-all-space ...` should be performed as mentioned in the previous version of the [doc](https://wiki.secondlife.com/wiki/2023_Consistent_Whitespace). Rerunning the script will just fix the inconsistencies produced by the merge.

**Comment by marchcat** [comment]
> If this was generated by passing the source code files through a processing tool, my preferred approach would be to run that over our sources first which should make the merge less painful.

It should work both ways when using `-Xignore-all-space` merge strategy.

**Comment by Ansariel** [comment]
Imagine merging this into the other development branches and either get tons of merge conflicts or having to do all this nonsense again...

**Comment by bennettgoble** [comment]
> That said, when Signal proposed something similar a few months ago it was quickly put on hold based on the strength of TPV feedback.

The switch was put on hold because there was an internal discussion over where to make the change (main branch vs a release branch.) --not related to the feedback.

**Comment by bennettgoble** [comment]
> That said, when Signal proposed something similar a few months ago it was quickly put on hold based on the strength of TPV feedback.

The switch was put on hold because there was an internal discussion over where to make the change (main branch vs a release branch.) --not related to any feedback.

The solution I had taken previously could be merged without manual conflict resolution, and I had tested it against Firestorm and other TPV codebases. :) @marchcat when you have information on the approach, could you put it in the PR's description? I think a PR of this size merits some explicit documentation on how to get it merged with minimal pain.

**Comment by Ansariel** [comment]
This feels like a disaster in the making because of something nobody asked for.

**Comment by Ansariel** [comment]
Is this disaster getting merged now or not?

**Comment by marchcat** [comment]
While a PR this big may seem like some sort of disaster, I tried to do a test merge on the Firestorm repo and had literally *five* conflicts. All of them were just caused by deleted files.

The current version of the document with the steps is [here](https://github.com/marchcat/sl-docs/blob/main/whitespace-merge-guide.md).

**Comment by Ansariel** [comment]
> While a PR this big may seem like some sort of disaster, I tried to do a test merge on the Firestorm repo and had literally _five_ conflicts. All of them were just caused by deleted files.

I did that the other week already, so: When is this disaster going to get merged?

**Comment by marchcat** [comment]
> When is this disaster going to get merged?

This disaster is going to be merged into `main` with Maint X release.

**Pull request merged**
