### PR TITLE
Update Japanese Translation

### PR DESCRIPTION
**Pull request by logue**

### CODE REVIEW

**Comment by logue** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by marchcat-pe** [comment]
Please change the target branch for this PR to `DRTVWR-577-maint-S`.

**Comment by logue** [comment]
I wasn't sure how to do it, but I merged with [`DRTVWR-577-maint-S`](https://github.com/secondlife/viewer/tree/DRTVWR-577-maint-S) and committed.
Perhaps the translation contains unnecessary elements or attributes.

Modifications are XML and HTML files in `/indra/newview/skins/default/xui/ja` 
 and `/indra/newview/skins/default/html/ja`.

**Comment by marchcat-pe** [comment]
> I wasn't sure how to do it, but I merged with [`DRTVWR-577-maint-S`](https://github.com/secondlife/viewer/tree/DRTVWR-577-maint-S) and committed. Perhaps the translation contains unnecessary elements or attributes.
> 
> Modifications are XML and HTML files in `/indra/newview/skins/default/xui/ja` and `/indra/newview/skins/default/html/ja`.

Thank you!
I'll check it. DRTVWR-577 has had some updates for the translations, so your commit should fit well into that viewer. However, given that your translation work is much deeper than mine, we should probably ignore all the related changes from DRTVWR-577.

**Comment by marchcat-pe** [comment]
@logue I've merged your fixes into a new branch, secondlife:SL-19669-jp-fix, to make the diff smaller by avoiding back-and-forth merges. Resolved all the conflicts as well, by taking your revisions for the existing ones and ignoring the deleted ones.

**Comment by marchcat-pe** [comment]
@logue Please check this PR: https://github.com/secondlife/viewer/pull/197

**Comment by akleshchev** [comment]
>I wasn't sure how to do it, but I merged with [DRTVWR-577-maint-S](https://github.com/secondlife/viewer/tree/DRTVWR-577-maint-S) and committed.

Normally you click the 'edit' button at the top, the part that says "secondlife:main" will turn into a dropbox, DRTVWR-577 branch should be there as an option. If you want, we can switch that ourselves but it will request conflic resolution from you either way.

**Comment by logue** [comment]
@akleshchev
I see. 

I will temporarily withdraw this push, create a branch from `DRTVWR-577-maint-S` to `DRTVWR-577-maint-S-jp-fix`, make a pull request again, and post it to [JIRA](https://jira.secondlife.com/browse/DRTVWR-577).

I think I can improve the quality of the translation a little more, so I'll be working on this branch for the time being.

If that policy is fine with you, please close it.

**Comment by akleshchev** [comment]
>If that policy is fine with you, please close it.
I'm fine with that, but it's marchcat who is reviewing.

**Comment by logue** [comment]
The translation has been completed, but it seems that DRTVWR-577-maint-S is gone.

**Comment by marchcat-pe** [comment]
Right. Please leave this PR as is for now, I'll give you an update soon.

**Comment by marchcat-pe** [comment]
@logue, thank you very much for providing a zip file. I ended up using it for an integration.
It saved some time by eliminating the need to resolve merge issues, thereby streamlining the overall changes.

These changes will be integrated into Maint T (DRTVWR-580) after being reviewed by our QA team as part of a larger translation-related project.

Please check this PR: https://github.com/secondlife/viewer/pull/229

**Comment by marchcat-pe** [comment]
Closing this one in favor of #229.

**Pull request closed without merging**
