### PR TITLE
Yuzuru20231125:fix of XML Header / UTF-8 BOM / EOF / name attribute duplicate of en and ja folder

### PR DESCRIPTION
**Pull request by YuzuruJewell**
I only update  xml files of "en" and "ja" folder of indra/newview/skins/default/xui
I updated following things.
-  fix XML header
- delete UTF-8 BOM
- delete \n before EOF
- name attribute duplicate of en and ja folder
and I updated Japanese translation of xml files of "ja" folder.
Please check it.

### CODE REVIEW

**Comment by YuzuruJewell** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ansariel** [comment]
The changes to the English files are completely unnecessary.

**Comment by YuzuruJewell** [comment]
I rewrote the xui XML files so that they can be processed by the tools I created.
I think that fluctuations in the notation of XML headers should be removed so that they can be processed accurately by programs. If the header is incorrect, the tool will not be able to read it.
I rewrote the name attribute of the XML files below. If these overlap, the XML files in the ja folder will not be able to find the corresponding node.

/indra/newview/skins/default/xui/en/floater_about_land.xml
/indra/newview/skins/default/xui/en/floater_beacons.xml
/indra/newview/skins/default/xui/en/floater_model_preview.xml
/indra/newview/skins/default/xui/en/floater_pathfinding_linksets.xml
/indra/newview/skins/default/xui/en/floater_preferences_graphics_advanced.xml
/indra/newview/skins/default/xui/en/floater_scene_load_stats.xml
/indra/newview/skins/default/xui/en/floater_snapshot.xml
/indra/newview/skins/default/xui/en/floater_test_layout_stacks.xml
/indra/newview/skins/default/xui/en/floater_test_line_editor.xml
/indra/newview/skins/default/xui/en/floater_test_textbox.xml
/indra/newview/skins/default/xui/en/floater_test_text_editor.xml
/indra/newview/skins/default/xui/en/floater_test_widgets.xml
/indra/newview/skins/default/xui/en/floater_translation_settings.xml
/indra/newview/skins/default/xui/en/floater_world_map.xml
/indra/newview/skins/default/xui/en/fonts.xml
/indra/newview/skins/default/xui/en/menu_navbar.xml
/indra/newview/skins/default/xui/en/menu_settings_gear.xml
/indra/newview/skins/default/xui/en/menu_topinfobar.xml
/indra/newview/skins/default/xui/en/mime_types.xml
/indra/newview/skins/default/xui/en/panel_group_creation_sidetray.xml
/indra/newview/skins/default/xui/en/panel_notification_list_item.xml
/indra/newview/skins/default/xui/en/panel_performance_preferences.xml
/indra/newview/skins/default/xui/en/panel_preferences_advanced.xml
/indra/newview/skins/default/xui/en/panel_preferences_sound.xml
/indra/newview/skins/default/xui/en/panel_profile_pick.xml
/indra/newview/skins/default/xui/en/panel_volume_pulldown.xml
/indra/newview/skins/default/xui/en/sidepanel_item_info.xml
/indra/newview/skins/default/xui/en/menu_picks.xml
/indra/newview/skins/default/xui/en/menu_places_gear_landmark.xml
/indra/newview/skins/default/xui/en/panel_dummy_clothing_list_item.xml
/indra/newview/skins/default/xui/en/panel_main_inventory.xml

By modifying the XML files in the en folder, I automatically generate the XML files in the ja folder using the original dictionary from the XML files in the en folder.

**Comment by Ansariel** [comment]
The tools you use are apparently not working correctly then, because the files are all valid XML according to the XML specification, esp. https://www.w3.org/TR/xml/#sec-white-space and https://www.w3.org/TR/xml/#sec-line-ends

Just run the files through one (or more) of the various XML validators out there and you will see there is exactly 0 need for pointlessly changing whitespaces and end of lines!

**Comment by marchcat-pe** [comment]
Thanks for the contribution!

The change is huge, I'll review it when able...

**Comment by marchcat-pe** [comment]
> there is exactly 0 need for pointlessly changing whitespaces and end of lines for hundreds of files

Agree. When we have such changes, I usually remove them before integration anyway.

**Comment by YuzuruJewell** [comment]
I only update xml files of "en" and "ja" folder of indra/newview/skins/default/xui
I thought that the problem of the XML header, BOM presence, and line break code being inconsistent were obstacles to using the tool outputting xml files automatically, so I fixed it.
But following your policy of not making any changes that would not interfere with operation, I removed them.
I updated following things.

About ”en” folder
- Added an XML header to the XML file which not have it.
- Added standalone="yes" to the XML header which not have it.
- Fixed duplication of name attributes for nodes at the same level.
  Without this fix, the nodes in the XML files in the en folder cannot be overwritten because they cannot be logically identified in multilingual XML files.

About "ja" folder
- Deleted an XML file that did not have an XML file with the same name in the en folder.
- The structure is now the same as the XML file with the same name in the en folder.
- The Japanese translation has been updated to make it easier to understand.

Remaining issues
There are still parts where the Japanese text does not fit into the specified display area. I am continuing to make adjustments to ensure consistency with other parts of the Japanese language as far as I can find by examining the XML file.
Please check it.

**Comment by marchcat-pe** [comment]
Thank you for the improvements.

These XML headers should not pose a problem for any tool, so we can usually leave them as they are.
Besides that, I see the specific parts of the translation that you have corrected. Will integrate them into a broader translation update.

**Pull request closed without merging**
