### PR TITLE
AIS/Thumbnails post merge fixes

### PR DESCRIPTION
**Pull request by akleshchev**

### CODE REVIEW

**Review by marchcat-pe — APPROVED** [review]
Thank you!

**Comment by marchcat-pe** [comment]
Should we add this to W and X as well?

**Comment by akleshchev** [comment]
>Should we add this to W and X as well?
Probably not, W has too high of a crashrate at the moment, it's unlikely to release first and X is only in planing.

**Comment by marchcat-pe** [comment]
Ok, let's just pick it up from here then.

**Comment by akleshchev** [comment]
Added 'apr crash' crashfix to the list since fix seems to be working well in maint-X and is it is our top crasher.

**Review by maxim-productengine — APPROVED** [review]

**Pull request merged**
