### PR TITLE
#2271 BugSplat Crash #1504299: LLFocusableElement::~LLFocusableElement(79)

### PR DESCRIPTION
**Pull request by LLGuru**

### CODE REVIEW

**Review by akleshchev — CHANGES_REQUESTED** [review]
If it was allocated it should be deallocated, this merely introduces a memory leak.

**Review by marchcat — CHANGES_REQUESTED** [review]
Right. It should not depend on isExiting() and should probably looks like this:
```
        if (mFocusLostCallback)
        {
            delete mFocusLostCallback;
            mFocusLostCallback = nullptr;
        }
        // and so on...
```

**Comment by akleshchev** [comment]
Aditionally this crash can happen without shutdown:
https://app.bugsplat.com/v2/crash?database=SecondLife_Viewer_2018&id=1496385

**Review by marchcat — APPROVED** [review]

**Review by akleshchev — APPROVED** [review]
I don't see how this going to fix the crash. But it won't hurt and might actually reveal more info.

**Pull request merged**
