### PR TITLE
Clean up for loops in llappearance to use C++11 range based for loops

### PR DESCRIPTION
**Pull request by Fawrsk**
I've also combined three loops into one within LLWearables::revertValues()

### CODE REVIEW

**Comment by Fawrsk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Fawrsk** [comment]
recheck

**Review by akleshchev — APPROVED** [review]
Looks good, but will ask someone to doublecheck mSavedVisualParamMap, it's odd that it was added in three steps without any clear reason to.

P.S. Studio often refuses to properly explain what's inside "auto" which makes code harder to read. Please avoid using "auto" at least for variables of non-obvious type like "mChildren" - name is too generic and does not explain what's inside. Replacing "auto child_info" with something like "bones_t::value_type child_info" or at least "auto bone_info" is a lot more readable.

**Comment by akleshchev** [comment]
Happy new year! Thank you for the contribution.

**Comment by akleshchev** [comment]
This appears to be your first contribution. SL maintains a list of contributors in doc/contributions.txt. Do you want to be added there under name Fawrsk?

**Pull request merged**
