### PR TITLE
Fix nonnull error in gcc version 13 on Linux.

### PR DESCRIPTION
**Pull request by AiraYumi**
I discovered this while trying to build FirestormViewer with gcc13 on Linux.

Since no error occurs in block_timer_tree_df_iterator_t in the first half of the file, I adjusted it accordingly.

### CODE REVIEW

**Comment by Ansariel** [comment]
You probably want to change the target to one of the maintenance branches.

**Comment by AiraYumi** [comment]
It is possible to switch if you know which maintenance branch you prefer.

**Comment by Ansariel** [comment]
I'm not with LL, so I can't tell you which one to choose. I would try the 587 or 588 one.

**Comment by AiraYumi** [comment]
try it.

**Comment by marchcat-pe** [comment]
@AiraYumi thank you for this contribution! It's greatly appreciated.

We will integrate it into a future maintenance release.

**Comment by marchcat-pe** [comment]
> I'm not with LL, so I can't tell you which one to choose. I would try the 587 or 588 one though.

@Ansariel, just FYI, due to our testing/releasing schedule, the highest number of the `DRTVWR-[number]-maint-[letter]` branches is the safest option to use.

**Review by marchcat-pe — APPROVED** [review]

**Comment by marchcat-pe** [comment]
Integrated manually into [DRTVWR-588-maint-W](https://github.com/secondlife/viewer/compare/DRTVWR-588-maint-W) to avoid the merge commit: https://github.com/secondlife/viewer/commit/7e6578dc0f71fa969d6b301fd3d3ef4090d68d50

This PR can be closed.

**Pull request closed without merging**
