### PR TITLE
Feature/linux gtk removal

### PR DESCRIPTION
**Pull request by Nicky-D**
This will remove the last obsolete parts of LL_GTK
This source is not used anymore, would be highly outdated (targeting GTK2 ) and could not even be used, as there is no GTK 3P.

### CODE REVIEW

**Review by marchcat — CHANGES_REQUESTED** [review]
Thank you for the contribution!

We have two build errors so far:

```
/home/runner/work/viewer/viewer/indra/newview/llfilepicker.cpp:1165:11: error: enumeration value 'FFSAVE_GLTF' not handled in switch [-Werror,-Wswitch]
                switch ((ESaveFilter) filter)
                        ^~~~~~~~~~~~~~~~~~~~
/home/runner/work/viewer/viewer/indra/newview/llfilepicker.cpp:1228:11: error: enumeration values 'FFLOAD_GLTF', 'FFLOAD_MATERIAL', and 'FFLOAD_MATERIAL_TEXTURE' not handled in switch [-Werror,-Wswitch]
                switch ((ELoadFilter) filter)
                        ^~~~~~~~~~~~~~~~~~~~
```

**Comment by Nicky-D** [comment]
> Thank you for the contribution!
> 
> We have two build errors so far:
> 
> ```
> /home/runner/work/viewer/viewer/indra/newview/llfilepicker.cpp:1165:11: error: enumeration value 'FFSAVE_GLTF' not handled in switch [-Werror,-Wswitch]
>                 switch ((ESaveFilter) filter)
>                         ^~~~~~~~~~~~~~~~~~~~
> /home/runner/work/viewer/viewer/indra/newview/llfilepicker.cpp:1228:11: error: enumeration values 'FFLOAD_GLTF', 'FFLOAD_MATERIAL', and 'FFLOAD_MATERIAL_TEXTURE' not handled in switch [-Werror,-Wswitch]
>                 switch ((ELoadFilter) filter)
>                         ^~~~~~~~~~~~~~~~~~~~
> ```

Thank you for starting the builds. I fixed those missing cases. Sadly I do not get the error locally, so it is a bit of a shot in the dark and I hope there won't be any more incoming

**Comment by marchcat** [comment]
Thanks, starting a new build.

**Comment by Nicky-D** [comment]
@marchcat fyi, while looking at this I got a feeling those filetypes are also not handled for OSX (at least partially).

I suggest someone with access to a Mac giving that a short investigation.

**Review by marchcat — APPROVED** [review]

**Pull request merged**
