### PR TITLE
2024.06 Atlasaurus

### PR DESCRIPTION
**Pull request by brad-linden**
as of = 2024-08-23 for RC deploy
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2325c4ba3a-atlasaurus
cohort = Atlasaurus
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2325c4ba3a-atlasaurus
desired = 10000

relnotes:

### Atlasaurus

This release marks the beginning of a new alphabet of releases which will be themed after Dinosaurs!

Starting with the almighty Atlasaurus (not to be confused with the almighty [A](https://wiki.secondlife.com/wiki/File:Atlasaurus.webp)tlas Linden). This titan herbivore is predicted to be 20m long and weighing 15 tons. It was discovered in the Atlas Mountains of Morocco where the titan Atlasaurus was said to hold up the heavens.

This Atlasaurus release brings the following almighty features: 

- Mirrors are disabled by default now and may still be enabled if you choose.
- Options to help with taking multiple objects so you can choose whether to take them all into your inventory as one or separately as individual objects. 
- Stop rendering those other avatars with the Avatar Display setting now found in Preferences>Graphics which allows prioritization of rendering your friends. (For those recording a video or taking a photo, a "Render Only Friends" setting is temporarily located at Develop->Avatar->Character Tests->Render Only Friends.)  
- Too bright? Control the amount of lights rendered with the new Max. Nearby Lights slider found in Advanced Graphics Settings.
- Better MOAP URL handling has also been implemented here in order for users to not only be able to CTRL+C or Cmd+C copy but also to see decoded URL payloads for easy inspection.
- Preview what your GLTF models _may_ look like in Second Life! While editing a prim, check out the preview setting via Develop->GLTF->Open. Please note that this feature is still in the early stages of development and that GLTF models will only appear locally. 

WebRTC Voice has also been merged into this release. Please see our blog post for more details: https://community.secondlife.com/blogs/entry/15626-coming-to-an-agni-region-near-you-an-update-on-changes-to-voice/

Plus many bugs have been squashed!

### CODE REVIEW

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c13eba1-2024.06

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2308f2236-atlasaurus

**Comment by marchcat** [comment]
Should we now add this back to https://github.com/secondlife/viewer/milestone/9?

**Comment by Dan-Linden** [comment]
| Atlasaurus RC 7.1.9.9620320242 | Result | Comment | 
|---|---|---|
| secondlife/iqa#266 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
There are 2 issues which would normally be blockers:
https://github.com/secondlife/viewer/issues/1826
https://github.com/secondlife/viewer/issues/1839

We are okay to ship this to a very small cohort just to get it on the downloads page. We will ask users who report performance issues to try this viewer to see if there is an improvement.


Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | MaxSecure - Win.MxResIcn.Heur.Gen <br> SecureAge - Malicious |
| SLVoice.exe | MaxSecure - Win.MxResIcn.Heur.Gen |
| dullahan_host.exe | MaxSecure - Win.MxResIcn.Heur.Gen |
| BsSndRpt.exe | MaxSecure - Win.MxResIcn.Heur.Gen |

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2308f2236-atlasaurus

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b6447de-atlasaurus

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233e4b235-atlasaurus

**Comment by AtlasLinden** [comment]
| Atlasaurus RC 7.1.9.9981869229 | Result | Comment | 
|---|---|---|
| secondlife/iqa#286 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
No blockers. 
The same Mac and Win crash reports can differ on Bugsplat: https://github.com/secondlife/viewer/issues/2043

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Atlasaurus RC Approved
viewer = 7.1.9.9981869229
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233e4b235-atlasaurus
cohort = Atlasaurus
desired = 500

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233e4b235-atlasaurus

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23002be0f-atlasaurus

**Comment by kylelinden** [comment]
Cohort increased to 2500

**Review by kylelinden — APPROVED** [review]
Atlasaurus RC Approved
viewer = 7.1.9.10220184061
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23002be0f-atlasaurus
cohort = Atlasaurus
desired = 3000

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23002be0f-atlasaurus

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233b2c32f-atlasaurus

**Comment by AtlasLinden** [comment]
| Atlasaurus RC 7.1.9.10326512121 | Result | Comment | 
|---|---|---|
| secondlife/iqa#306 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
No blockers. 

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Atlasaurus RC Approved
viewer = 7.1.9.10326512121
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233b2c32f-atlasaurus 
cohort = Atlasaurus
desired = 3000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233b2c32f-atlasaurus

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235f26ba8-atlasaurus

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23738b39f-atlasaurus

**Comment by Dan-Linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23738b39f-atlasaurus

**Comment by AtlasLinden** [comment]
| Atlasaurus RC 7.1.9.10479800881 | Result | Comment | 
|---|---|---|
| secondlife/iqa#311 Acceptance, Integration & Additional tests | Failed | See notes |
| **Overall Result** | **Failed** | **NOT OK to ship RC** | 

**NOTES**
Blocker: https://github.com/secondlife/viewer/issues/2376
Remaining issues to test were also deferred due to this issue.

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2333c7a87-atlasaurus

**Comment by kylelinden** [comment]
On Friday 9/16 maint B, C and WebRTC cohorts closed and VVM updated to direct them to update to Atlasaurus RC. New Atlasaurus RC cohort size increased to 10k.

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2333c7a87-atlasaurus

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2325c4ba3a-atlasaurus

**Comment by AtlasLinden** [comment]
| Atlasaurus RC 7.1.9.10515727195 | Result | Comment | 
|---|---|---|
| secondlife/iqa#315 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
No blockers. 

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Atlasaurus RC approved
viewer = 7.1.9.10515727195
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2325c4ba3a-atlasaurus
cohort = Atlasaurus
desired = 10000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2325c4ba3a-atlasaurus

**Comment by kylelinden** [comment]
Atlasaurus+WebRTC approved for default release. Improved FPS and crashrate.
viewer = 7.1.9.10515727195
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2325c4ba3a-atlasaurus
cohort = Atlasaurus
desired =

**Pull request merged**
