### PR TITLE
2024.09 ExtraFPS

### PR DESCRIPTION
**Pull request by brad-linden**
as of = 2024-12-17 for RC deploy
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb5fa35-ExtraFPS
cohort = ExtraFPS
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb5fa35-ExtraFPS
desired = 5000
relnotes: 

### Second Life Viewer - ExtraFPS 

Extra performance boosts have been added to this release for that extra FPS. The enhanced texture memory tracking, broader hardware compatibility and higher FPS gain are sure to provide a smoother Second Life experience.

With ExtraFPS also comes extra features:

- New "HDR and Emissive" found in Advanced, Graphics settings, specifically to increase performance on older machines.
  - This mode enables/disables HDR and Emissive which will make much of the world appear like it did before 7.x based viewers. 
- Filters on object Inventory to help manage those largely stocked prims.
- A new checkbox to show/hide the voice dot above avatars (see Preferences>Sound & Media). 
- Your dot on the minimap is now white in order to distinguish against all your nearby friends.
- Graphics folks rejoice as we introduce:
  - New Antialiasing setting SMAA.
  - Contrast Adaptive Sharpening.
  - Additional tonemapper: Khronos Neutral. (Presently, can be set via Advanced Graphics Preferences)
- Exposure has been reset to 1.0 
- Default tonemapper reset to ACES with small mix towards linear 

Further changes include crash fixes, squashed bugs and webRTC improvements. See below for more details.

We welcome your feedback about these new changes, please let us know by filing an issue at https://feedback.secondlife.com

### CODE REVIEW

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b589d39-ExtraFPS

**Comment by AtlasLinden** [comment]
| ExtraFPS 7.1.11.10947335521 | Result | Comment |
|---|---|---|
| secondlife/iqa#346 Acceptance & Integration tests  | Failed | New Issues |
| secondlife/iqa#348 Additional Testing | Failed | Reproduced issues |
| **Overall Result** | **Failed** | **NOT OK to ship RC** |

**NOTES**
Failed due to showstopper issues found.

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2364c055f-ExtraFPS

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved
viewer = 7.1.11.11074622243
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2364c055f-ExtraFPS
cohort = ExtraFPS
desired = 1000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2364c055f-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b71343e-ExtraFPS

**Comment by AtlasLinden** [comment]
| ExtraFPS 7.1.11.11296522354 | Result | Comment |
|---|---|---|
| secondlife/iqa#367 Acceptance & Integration tests  | Passed | Passed |
| secondlife/iqa#366 Additional Testing | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** |

**NOTES**
Voice issue reported was in regards to a Vivox outage that occurred during testing and is not related to this build.

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved
viewer = 7.1.11.11296522354
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b71343e-ExtraFPS
cohort = ExtraFPS
desired = 2000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b71343e-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23cbd594a-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231a79095-ExtraFPS

**Comment by AtlasLinden** [comment]
| ExtraFPS RC 7.1.11.11565212741 | Result | Comment |
|---|---|---|
| secondlife/iqa#375 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** |

**NOTES**
None

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved
viewer = 7.1.11.11565212741
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231a79095-ExtraFPS
cohort = ExtraFPS
desired = 2000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231a79095-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2313c0708-ExtraFPS

**Comment by AtlasLinden** [comment]
| ExtraFPS RC 7.1.11.11750364439 | Result | Comment |
|---|---|---|
| secondlife/iqa#381 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** |

**NOTES**
None

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved
viewer = 7.1.11.11750364439
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2313c0708-ExtraFPS
cohort = ExtraFPS
desired = 3000

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2313c0708-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23c654dac-ExtraFPS

**Comment by AtlasLinden** [comment]
| ExtraFPS RC 7.1.11.11864501455 | Result | Comment |
|---|---|---|
| secondlife/iqa#386 Acceptance, Integration & Additional tests | Failed | Failed |
| **Overall Result** | **Failed** | **NOT OK to ship RC** |

**NOTES**
Blocker: https://github.com/secondlife/viewer/issues/3093

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b7924f7-ExtraFPS

**Comment by AtlasLinden** [comment]
| ExtraFPS RC 7.1.11.11982653819 | Result | Comment |
|---|---|---|
| secondlife/iqa#395 Acceptance, Integration & Additional tests | Failed | Failed |
| **Overall Result** | **Failed** | **NOT OK to ship RC** |

**NOTES**
Blockers: https://github.com/secondlife/viewer/issues/2991
https://github.com/secondlife/viewer/issues/3145

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23a90377d-ExtraFPS

**Comment by AtlasLinden** [comment]
| ExtraFPS RC 7.1.11.12041172537 | Result | Comment |
|---|---|---|
| secondlife/iqa#401 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship ONLY as RC** |

**NOTES**
This build incorporates many QoL fixes that improve upon the previous RC.
However, QA does NOT recommend promoting this build to Default due to new issues found.
Shipping also requires an update to the release notes regarding the new "Vintage mode"

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved.
viewer = 7.1.11.12041172537
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23a90377d-ExtraFPS
cohort = ExtraFPS
desired = 4000

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23a90377d-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233f6d55f-ExtraFPS

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved.
viewer = 7.1.11.12150664210
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233f6d55f-ExtraFPS
cohort = ExtraFPS
desired = 4000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%233f6d55f-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23412b3db-ExtraFPS

**Comment by Dan-Linden** [comment]
| ExtraFPS RC 7.1.11.12208292573 | Result | Comment |
|---|---|---|
| secondlife/iqa#409 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Failed** | **Not ok to ship RC** |

**NOTES**
Only 1 of the fixed issues passed QA, so it's not worth the disruption to ship this.

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2397826b5-ExtraFPS

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23eff4626-ExtraFPS

**Comment by Dan-Linden** [comment]
| ExtraFPS RC 7.1.11.12306234817 | Result | Comment |
|---|---|---|
| secondlife/iqa#411 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** |

**NOTES**
Showstoppers https://github.com/secondlife/viewer/issues/2590 and https://github.com/secondlife/viewer/issues/3106 did not pass QA, but this build has several important fixes so we should ship this.

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |
| uninstaller.exe |  Bkav Pro - W32.AIDetectMalware |

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved
viewer = 7.1.11.12306234817
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23eff4626-ExtraFPS
cohort = ExtraFPS
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23eff4626-ExtraFPS

**Comment by Dan-Linden** [comment]
IQA https://github.com/secondlife/iqa/issues/418

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb5fa35-ExtraFPS

**Comment by Dan-Linden** [comment]
| ExtraFPS RC 7.1.11.12363455226 | Result | Comment |
|---|---|---|
| secondlife/iqa#419 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** |

**NOTES**


Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | SecureAge - Malicious |
| uninstaller.exe |  Bkav Pro - W32.AIDetectMalware |

**Review by kylelinden — APPROVED** [review]
ExtraFPS RC approved
viewer = 7_1_11_12363455226
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb5fa35-ExtraFPS
cohort = ExtraFPS
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb5fa35-ExtraFPS

**Comment by kylelinden** [comment]
ExtraFPS approved for promotion to default release.
viewer = 7_1_11_12363455226
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb5fa35-ExtraFPS
cohort = ExtraFPS
desired =

**Pull request merged**
