### PR TITLE
Display parcel name when clicking on a parcel on the world map

### PR DESCRIPTION
**Pull request by Ansariel**
Special request by @RyeMutt : Tracker info will now also show the name of the parcel when clicking a location on the world map: https://gyazo.com/06b2412c1fd79245446b1a25fecd5638

### CODE REVIEW

**Review by marchcat — APPROVED** [review]
Thank you, @Ansariel!

**Review by akleshchev — APPROVED** [review]
Any suggestions for test plans? This looks like somthing should not only go over but have a permanent test plan for regression testing.

**Comment by bennettgoble** [comment]
@akleshchev the feature looks pretty simple: "parcel name when clicking on a parcel on the world map" --QA will need to tack this onto the test plan. Should we get this merged?

**Comment by kylelinden** [comment]
That's nice addition. Thanks

**Pull request merged**
