### PR TITLE
ExtraFPS -> develop merge

### PR DESCRIPTION
**Pull request by brad-linden**

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

**Comment by marchcat** [comment]
Oh, I didn't notice it had auto-merge enabled. But that is convenient.

**Comment by brad-linden** [comment]
> Oh, I didn't notice it had auto-merge enabled. But that is convenient.

Yeah I turned on the option for enabling this,  I wasn't sure how to experiment with it without surprising people.  My hope is that this will reduce some of the motivation to skip checks

**Comment by marchcat** [comment]
> My hope is that this will reduce some of the motivation to skip checks

In this case, should we make the green build checks required as well?

**Comment by brad-linden** [comment]
> In this case, should we make the green build checks required as well?

I would definitely like to get that done.  I don't know for sure yet what impediments may still be in the way of doing that, but until we do know, I want to keep removing any possible impediments to that.

**Pull request merged**
