### PR TITLE
brad/tag release

### PR DESCRIPTION
**Pull request by brad-linden**
Allow manually dispatched workflow form to create tags for releases.

Screenshot 2024-06-20 at 5 22 51 PM

### CODE REVIEW

**Comment by brad-linden** [comment]
this isn't quite working yet.  It seems that it can create tags, but those tags don't trigger a build because they aren't "pushed"

**Comment by nat-goodspeed** [comment]
> this isn't quite working yet.

Still true, or resolved?

**Review by nat-goodspeed — APPROVED** [review]
I'm good with this.

Can `build.yaml` triggers be extended to notice the creation of a new tag?

**Comment by brad-linden** [comment]
> Can `build.yaml` triggers be extended to notice the creation of a new tag?

yes.  I have begun researching `workflow_run` triggers which I think can be used for that.  I'll do that experiment under another PR

**Pull request merged**
