### PR TITLE
Maintenance X

### PR DESCRIPTION
**Pull request by marchcat**
Following DRTVWR-591.

as of = 2024-05-08 for RC deploy
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2338c2a5b-x
cohort = Maintenance-X
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2338c2a5b-x
desired = 5000
relnotes:
### Maintenance Xenial eXpansion
Xenial - Hospitable, especially to visiting strangers or foreigners

X here marks the spot for many viewer usability improvements including:

- Saving you some clicks by allowing the deletion of folders containing worn items. No need to first detach those unwanted demo’s.
- In case you only wish to detach, Alt+Shift+R will now detach selected attachments so you can remove those less fashionable items at rapid speed.
- The time format has been changed to show the more superior SLT instead of PDT.
- The group join fee will be shown when leaving a group so you can be extra sure you want to leave it.
- Shift+Alt+N will now open the Notifications floater for those of you that may have forgotten how to open it.
- Saving you more clicks as group notices can now be accessed directly from the People floaters Groups tab. Hover that mouse cursor over the group name for access.
- Said group notices will now default as being sorted by date with the newest first \o/

See more along with plenty of bug fixes below.

#### Known Issues: 

Unable to delete folders from 'Marketplace listings' floater.

### CODE REVIEW

**Comment by marchcat-pe** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2370d5d91-x

**Comment by AtlasLinden** [comment]
| Maint X RC 7.1.3.7721015131 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#102 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Cynet - Malicious (score: 100) <br> SecureAge - Malicious |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Review by kylelinden — APPROVED** [review]
Approved RC
viewer = 7.1.3.7721015131 
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2370d5d91-x
cohort = Maintenance-X
desired = 3000

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2325251c3-x

**Comment by AtlasLinden** [comment]
| Maint X RC 7.1.4.8148263040 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#151 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers. 
New and reproduced bugs are not considered blockers for this build.

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Cynet - Malicious (score: 100) <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Cynet - Malicious (score: 100) <br> Elastic - Malicious (moderate Confidence) <br> SecureAge - Malicious |

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2356c88b8-x

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23f496800-x

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23007d92b-x

**Comment by AtlasLinden** [comment]
| Maint X RC 7.1.4.8333131717 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#163 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers. 

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Elastic - Malicious (moderate Confidence) <br> SecureAge - Malicious |

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231ae6f5d-x

**Comment by AtlasLinden** [comment]
| Maint X RC 7.1.5.8443777128 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#176 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers. 
Crash spotted on IQA already exists in current default release
https://github.com/secondlife/viewer/issues/1080

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Elastic - Malicious (moderate Confidence) <br> SecureAge - Malicious |

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb2bf0e-x

**Comment by AtlasLinden** [comment]
| Maint X RC 7.1.6.8709279750 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#198 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers. 

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Elastic - Malicious (moderate Confidence) <br> SecureAge - Malicious |
| SLVoice.exe | Bkav Pro - W64.AIDetectMalware |
| uninst.exe | Bkav Pro - W32.AIDetectMalware |

**Review by kylelinden — APPROVED** [review]
Maint X RC approved.
viewer = 7.1.6.8709279750
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb2bf0e-x
cohort = Maintenance-X
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23bb2bf0e-x

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235ad488a-x

**Comment by Dan-Linden** [comment]
| Maint X RC 7.1.6.8758996787 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#203 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Bkav Pro - W64.AIDetectMalware <br> SecureAge - Malicious |
| SLVersionChecker.exe | Elastic - Malicious (moderate Confidence) <br> SecureAge - Malicious |
| SLVoice.exe | Bkav Pro - W32.AIDetectMalware |
| uninst.exe | Bkav Pro - W32.AIDetectMalware |

**Review by kylelinden — APPROVED** [review]
Maint X RC approved
viewer = 7.1.6.8758996787
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235ad488a-x
cohort = Maintenance-X
desired = 5000

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%237719d54-x

**Review by vir-linden — COMMENTED** [review]
We already have a .clang format file. Do we want to maintain both?

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2338c2a5b-x

**Comment by AtlasLinden** [comment]
| Maint X RC 7.1.7.8974243247 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#214 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers but secondlife/viewer-private/issues/236 should be mentioned in release notes as a known issue.

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Elastic - Malicious (moderate Confidence) <br> SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Maint X RC approved.
viewer = 7.1.7.8974243247
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2338c2a5b-x
cohort = Maintenance-X
desired = 5000

**Comment by vir-linden** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2338c2a5b-x

**Comment by kylelinden** [comment]
Deployed Maint X RC 7.1.7.8974243247 approved for promotion to default release.

**Pull request closed without merging**
