### PR TITLE
SL-20743 Use LLMutex in LLImageBase for internal data thread-safety (update)

### PR DESCRIPTION
**Pull request by LLGuru**

### CODE REVIEW

**Review by marchcat-pe — APPROVED** [review]

**Review by akleshchev — APPROVED** [review]
Can you use std::shared_mutex instead? Like: read operations getting shared locks and write operations getting exlusive locks.

**Comment by LLGuru** [comment]
> Can you use std::shared_mutex instead? Like: read operations getting shared locks and write operations getting exlusive locks.

Yes, I can, and I do: `mSharedMutex` is of type `std::shared_mutex`
image

**Comment by akleshchev** [comment]
My consern is that maintaining a list of threads is an unneeded overhead, a thread local 'islocked' bool or  something similar should have been enough.

**Comment by akleshchev** [comment]
Could you have used a thread_local integer to store how many times it was locked instead of maintaining an actual list?

**Comment by AtlasLinden** [comment]
Archived issue: https://github.com/secondlife/jira-archive-internal/issues/71134

**Pull request merged**
