### PR TITLE
Fix Visual Studio complaints in LLTrans

### PR DESCRIPTION
**Pull request by Ansariel**

### CODE REVIEW

**Review by marchcat — APPROVED** [review]
Thank you!

**Comment by marchcat** [comment]
This change broke the unit test:
```
/Users/runner/work/viewer/viewer/indra/newview/tests/lldateutil_test.cpp:60:22: error: out-of-line definition of 'getCountString' does not match any declaration in 'LLTrans'
std::string LLTrans::getCountString(const std::string& language, const std::string& xml_desc, S32 count)
                     ^~~~~~~~~~~~~~
1 error generated.
```

**Comment by Ansariel** [comment]
Should be fixed now.

**Comment by marchcat** [comment]
Awesome, thank you!

**Pull request merged**
