### PR TITLE
Maintenance W

### PR DESCRIPTION
**Pull request by marchcat**
Following DRTVWR-588.

relnotes:
### Maintenance Wascally Wampires

Spooky season has passed and yet we still have enchantments for many frightening crashes users have been seeing.

Some rituals have been made to our translation services including reviving the previously petrified Google Translate which will enable users worldwide to be able to read your funny, spooky jokes, including:

Why did the ghost cross the road?
To return from the other side.
(Note: Some jokes likely do not translate well into other languages/cultures)

Lost your voice after quickly restarting your viewer? (Or from laughing too hard at that joke?) No need to be afraid. This nefarious bug has been sent to the grave with this release along with a number of other eerie issues listed below.

### CODE REVIEW

**Comment by marchcat-pe** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23dd09848-w

**Comment by marchcat-pe** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f0a5a3-w

**Comment by AtlasLinden** [comment]
| Maint W RC 7.1.3.7701974306 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#99 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Cynet - Malicious (score: 100) <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious <br> Yandex - Trojan.PyInstaller!7Lr0/TMk2fI |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Review by kylelinden — APPROVED** [review]
Approved for RC update 7.1.3.7701974306 
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f0a5a3-w
cohort = Maintenance-W
desired = 3000

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%239f0a5a3-w

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235bd9c86-w

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235e697cc-w

**Comment by AtlasLinden** [comment]
| Maint W RC 7.1.3.7983616888 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#138 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious |
| slvoice.exe | Cynet - Malicious (score: 100) |

**Review by kylelinden — APPROVED** [review]
Approved maint w RC
viewer: 7.1.3.7983616888
build: https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%235e697cc-w 
cohort: Maintenance-W
desired: 3000

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%236d077c9-w

**Comment by AtlasLinden** [comment]
| Maint W RC 7.1.3.7983616888 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#148 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Cynet - Malicious (score: 100) <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Approved Maint W for RC
viewer = 7.1.4.8113624779
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%236d077c9-w
cohort = Maintenance-W
desired = 3000

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%236d077c9-w

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23091ee67-w

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231161262-w

**Comment by AtlasLinden** [comment]
| Maint W RC 7.1.4.8300292622 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#164 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2378174fc-w

**Comment by AtlasLinden** [comment]
| Maint W RC 7.1.5.8443591509 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#175 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Maint W RC approved
viewer = 7.1.5.8443591509
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2378174fc-w
cohort = Maintenance-W
desired = 3000

**Comment by kylelinden** [comment]
Please promote Maint W to default release.

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2378174fc-w

**Pull request merged**
