### PR TITLE
GLTF PBR Maint 2

### PR DESCRIPTION
**Pull request by brad-linden**
relnotes: 

Another collection of fixes for our new PBR Materials feature which was recently released.

### CODE REVIEW

**Comment by brad-linden** [comment]
latest build: https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23586e4cd-gltf-maint2

**Comment by Dan-Linden** [comment]
IQA 86. https://github.com/secondlife/iqa/issues/86

**Comment by brad-linden** [comment]
updated latest build: https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23ea4dc1f-gltf-maint-2

**Comment by nat-goodspeed** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23ea4dc1f-gltf-maint-2

is what our updated release scripts will find.

**Comment by Dan-Linden** [comment]
| GLTF Materials Maint 2 RC 7.1.3.7648599679 | Result | Comment | 
|---|---|---|
| secondlife/iqa#96 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship RC** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Cynet - Malicious (score: 100) <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious <br> Yandex - Trojan.PyInstaller!7Lr0/TMk2fI |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Comment by Dan-Linden** [comment]
Failed QA of 7.1.3.7648599679 for https://github.com/secondlife/viewer/issues/724

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2323d44cb-gltf-maint2

**Comment by Dan-Linden** [comment]
| GLTF Materials Maint 2 RC 7.1.3.7821226606 | Result | Comment | 
|---|---|---|
| secondlife/iqa#120 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious <br> Yandex - Trojan.PyInstaller!7Lr0/TMk2fI |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Comment by brad-linden** [comment]
I accidentally merged in the materials_featurettes branch.  I have force-pushed this back to the last build: https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2323d44cb-gltf-maint2

**Review by kylelinden — APPROVED** [review]
Approved gltf main 2 
viewer = 7.1.3.7821226606
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2323d44cb-gltf-maint2
cohort = GLTF PBR Maint 2
desired = 5000

**Comment by nat-goodspeed** [comment]
Please consider merging in the `gh-relnotes` branch #919. This branch is moderately likely to release soon, and we'd like to be able to leverage GitHub generated release notes.

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23258c0395-gltf-maint2

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%231013ea5-gltf-maint2

**Comment by brad-linden** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23dd74c2c-gltf-maint2

**Comment by Dan-Linden** [comment]
| GLTF Materials Maint 2 RC 7.1.4.8149792635 | Result | Comment | 
|---|---|---|
| secondlife/iqa#150 Acceptance, Integration & Additional tests | Passed | Passed |
| **Overall Result** | **Passed** | **OK to ship** | 

**NOTES**
No blockers

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | Cynet - Malicious (score: 100) <br> MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious |

**Review by kylelinden — APPROVED** [review]
Approved gltf main 2
viewer = 7.1.4.8149792635
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23dd74c2c-gltf-maint2
cohort = GLTF PBR Maint 2
desired = 5000

**Review by kylelinden — APPROVED** [review]

**Comment by kylelinden** [comment]
Approved for promotion to default release.

**Comment by nat-goodspeed** [comment]
deployed = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23dd74c2c-gltf-maint2

**Comment by Dan-Linden** [comment]
GLTF Maint 2 cleanup - https://docs.google.com/document/d/143tjFnzDfVtPOBwRg-7ZlgBjjEu-tgAjmRed230zp58/edit

**Pull request merged**
