### PR TITLE
Attempt to speed up which-branch's `pip3 install PyGithub`

### PR DESCRIPTION
**Pull request by brad-linden**

### CODE REVIEW

**Comment by brad-linden** [comment]
hmm this doesn't do what I want, bottleneck actually appears to be in the which-branch.py script itself

**Comment by brad-linden** [comment]
that doesn't sound that inefficient.  there are a small enough number of active branches at a given time (<500) that we should be able to iterate over them,  I still don't think it should take 3 minutes to do that

**Comment by nat-goodspeed** [comment]
Oho, but now that we have a preliminary `setvar` job, we could move branch detection there and do it once for all platforms!

**Comment by nat-goodspeed** [comment]
https://github.com/secondlife/viewer/commit/7e381d62a8e7f64f1bae96a8ef6b38316427381b

**Comment by brad-linden** [comment]
this approach seems unlikely to move the needle on build times, closing.

**Pull request closed without merging**
