### PR TITLE
Roll back to Xcode 14.0.1 to fix secondlife/viewer-private#347

### PR DESCRIPTION
**Pull request by brad-linden**
secondlife/viewer-private#347

### CODE REVIEW

**Review by akleshchev — APPROVED** [review]

**Comment by akleshchev** [comment]
How is mac build related to inventory? Is there some code that is ambigious and needs updating?

**Comment by brad-linden** [comment]
there is definitely a deeper problem here.  we will need to get a better fix going forward.

**Comment by marchcat** [comment]
Wow, that was unexpected. Can it be something related to the Apple silicon runner vs. Intel?

**Comment by brad-linden** [comment]
the macos 13 runners were still intel I think.  I am continuing to investigate with a focus on libc++ changes and container usage

**Pull request merged**
