### PR TITLE
Maintenance A (old)

### PR DESCRIPTION
**Pull request by marchcat**
relnotes:
### Maintenance A: Atlasaurus

This release marks the beginning of a new alphabet of Maintenance releases which will be themed after Dinosaurs!

Starting with the almighty Atlasaurus (not to be confused with the almighty Atlas Linden). This titan herbivore is predicted to be 20m long and weighing 15 tons. It was discovered in the Atlas Mountains of Morocco where the titan Atlasaurus was said to hold up the heavens.

This Atlasaurus release brings new options to help with taking multiple objects so you can choose whether to take them all into your inventory as one or separately as individual objects. Better MOAP URL handling has also been implemented here in order for users to not only be able to CTRL+C or Cmd+C copy but also to see decoded URL payloads for easy inspection.

Adding to this are some smaller fixes which are listed below.

### CODE REVIEW

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23165f7bf-a

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%232d8654d-a

**Comment by AtlasLinden** [comment]
relnotes:
### Maintenance A: Atlasaurus
This release marks the beginning of a new alphabet of Maintenance releases which will themed after Dinosaurs!

Starting with the almighty Atlasaurus (not to be confused with the almighty Atlas Linden). This titan herbivore is predicted to be 20m long and weighing 15 tons. It was discovered in the Atlas Mountains of Morocco where the titan Atlasaurus was said to hold up the heavens.

This Atlasaurus release brings new options to help with taking multiple objects so you can choose whether to take them all into your inventory as one or separately as individual objects. Better MOAP URL handling has also been implemented here in order for users to not only be able to CTRL+C or Cmd+C copy but also to see decoded URL payloads for easy inspection.
Adding to this are some smaller fixes which are listed below.

**Comment by AtlasLinden** [comment]
| Maint A RC 7.1.3.7878388412 RC | Result | Comment | 
|---|---|---|
| secondlife/iqa#130 Acceptance, Smoke & Additional tests | Failed | Failed |
| **Overall Result** | **FAILED** | **NOT OK to ship** | 

**NOTES**
Blocker: secondlife/triage/issues/84

Anti-virus false positive report:
| File | Security vendor analysis |
|---|---|
| slplugin.exe | MaxSecure - Trojan.Malware.300983.susgen <br> SecureAge - Malicious |
| SLVersionChecker.exe | Antiy-AVL - Trojan/Win32.Wacatac <br> Cynet - Malicious (score: 100) <br> SecureAge - Malicious |
| slvoice.exe | Cynet - Malicious (score: 100) |
| uninst.exe | Cynet - Malicious (score: 100) |

**Comment by nat-goodspeed** [comment]
Atlas, at Kyle's request, I'm making the relnotes extraction code pull the release notes header from the PR description instead of individual comments. To test that, I copied your relnotes comment to the PR description.

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%236b28567-a

**Comment by marchcat** [comment]
This includes `BOOL` -> `bool` change across the entire codebase, so regression testing is advised.

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2371ed198-a

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23dfbbad8-a

**Comment by AtlasLinden** [comment]
Latest builds still blocked on https://github.com/secondlife/triage/issues/84

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2315d4db0-a

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23ad64251-a

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23069ea06-a

**Comment by marchcat** [comment]
build = https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%230870539-a

**Comment by marchcat** [comment]
Closing in favor of #1722 to switch to the new branch naming scheme.

**Comment by marchcat** [comment]
New branch: `release/maint-a`

**Pull request closed without merging**
