### PR TITLE
Give control over thread queue's automatic shutdown

### PR DESCRIPTION
**Pull request by akleshchev**
queue can shutdown before parent thread is done

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

**Review by nat-goodspeed — COMMENTED** [review]
My question is: now that `WorkQueueBase` has `auto_shutdown`, why don't we remove that feature from `ThreadPoolBase`? Put differently, it seems to me the `auto_shutdown` flag passed to `ThreadPoolUsing` and its alias `ThreadPool` could _just_ pass through to `queue_t`, instead of engaging redundant support in `ThreadPoolBase`'s constructor.

**Comment by akleshchev** [comment]
>My question is: now that WorkQueueBase has auto_shutdown, why don't we remove that feature from ThreadPoolBase?

@nat-goodspeed Are you suggesting to remove mStopListener from ThreadPoolBase?

**Comment by nat-goodspeed** [comment]
Hmm, now that I'm looking at `ThreadPoolBase::close()`, I see that it does more than call `WorkQueueBase::close()`: it also joins the `ThreadPoolBase` threads. Sorry, my previous suggestion was ill-considered.

So this PR is about the case when we have a `WorkQueue` or `WorkSchedule`, _not_ associated with a `ThreadPool`, that shouldn't `close()` when `LLCoros` signals the start of viewer shutdown? Maybe it should instead listen for a later value of `"status"` ?

**Comment by akleshchev** [comment]
> Maybe it should instead listen for a later value of "status" ?

This is mostly for the sake of window thread which under normal circumstances needs to keep living long after event system dies.

**Comment by nat-goodspeed** [comment]
Okay, I see. In that case I agree with your earlier suggestion.

> Arguably I should be calling new queue_t(name, capacity, false) to let thread decide when it's ready to die.

If both `ThreadPoolBase` and `WorkQueueBase` see `auto_shutdown=true`, they register redundant listeners.

**Comment by akleshchev** [comment]
Updated with `new queue_t(name, capacity, false)`.

**Review by nat-goodspeed — APPROVED** [review]

**Pull request merged**
